language: node_js
os:
  'linux'
node_js:
  - 'node'
deploy:
  provider: npm
  on:
    branch: master
    tags: true
  email: 'gleydsonsr@gmail.com'
  cleanup: true
  api_token: '$NPM_TOKEN'

notifications:
  email:
    recipients:
    - gleydsonsr@gmail.com
    on_success: change
    on_failure: always